### ISSUE TITLE
Warning ⚠️ making credentials available to clients!

### ISSUE THREAD

**Issue by tomoliveri** [SwedishFighters/CrowdstrikeFix#1]
This will hand out the admin password in the clear in the generated post-install.sh which you’re making available to clients… 

This is super dangerous, obviously be careful doing it this way.

**Comment by SwedishFighters** [comment]
You are right and careful planning as well as monitoring (including monitoring active directory) is of course needed.
This is obviously mostly for those with 50 000 clients or more which need cleaning (to be able to fix on a massive scale).

**Comment by Aeyk** [comment]
A possible mitigation might be to create a domain user in an OU with delegated access to read the BitLocker key attribute and then cycle the key after it's done. Less exposure then a domain admin account.
